### PR TITLE
Fix clipping of non-int32 numbers

### PR DESCRIPTION
**Pull request by evpobr**

### CODE REVIEW

**Review by SoapGentoo — APPROVED** [review]
give a rationale why we can remove the conditional macros now?

**Comment by evpobr** [comment]
@umlaeute explained everything well #882.

**Comment by umlaeute** [comment]
@arthurt i haven't checked whether this PR removes *all* uses of `CPU_CLIPS_*`, or only those that are not about `int32_t`.
if the latter, than the `--disable-cpu-clip` flag still makes sense...

**Comment by umlaeute** [comment]
as a side note: you might also want to add some unit-tests for correct clipping behaviour.

it was by mere chance that we triggered the failing test in the `python-soundfile` package on our Debian infrastructure, as the package currently only runs the testsuite as part of the build process. and since `python-soundfile` itself is architecture independent (with all the architecture-specific parts in its dependencies, like e.g. `libsndfile`), we usually don't build the package on any architecture except for the default one (which is x86_64).
in contrast, the `libsndfile` testsuite is run on all architectures that can build the library.

it would have also helped (and saved me a lot of time), if I could have been certain from the beginning, in which component the issue actually originated. (finding bugs is hard enough in a software package itself; but if you have to chase down dependencies, it becomes truly awful)

**Comment by evpobr** [comment]
> @arthurt i haven't checked whether this PR removes _all_ uses of `CPU_CLIPS_*`, or only those that are not about `int32_t`. if the latter, than the `--disable-cpu-clip` flag still makes sense...

I applied your patch without changes:

https://salsa.debian.org/multimedia-team/libsndfile/-/blob/master/debian/patches/short_clipping.patch

**Comment by evpobr** [comment]
Let's merge this pull request, it's definitely useful. Then you can think about the details. @arthurt ?

**Pull request merged**
