### PR TITLE
sndfile-play: Add NetBSD support

### PR DESCRIPTION
**Pull request by alarixnia**

### CODE REVIEW

**Comment by evpobr** [comment]
Hi @alarixnia .

**Comment by alarixnia** [comment]
Hiii @evpobr

**Comment by evpobr** [comment]
Has it been tested with both Autotools and CMake?

**Comment by evpobr** [comment]
@SoapGentoo , can you take this PR?

**Review by mgorny — APPROVED** [review]
Just tested on NetBSD, plays sound.

**Review by SoapGentoo — CHANGES_REQUESTED** [review]
@alarixnia LGTM, can you please amend the manpage to mention NetBSD on the Solaris line too?

**Review by evpobr — APPROVED** [review]

**Pull request merged**
