### PR TITLE
Fix for Issue 643: Vorbis Seek Offset.

### LINKED ISSUE #643: missing samples when doing a partial read of ogg file from index till the end of file
Hi all,

We are in the process of upgrading from 1.0.28 to 1.0.30, and we noticed this issue in the new release.

Looks like it happens when you seek to a start index that is >=88201 before reading. The read data seems to match the data at end of the file, but some samples right after the start index are missing. The number of missing samples seems to always be a power of two.

Here is simple reproduction code with an example:

```
#include <iostream>
#include "sndfile.h"

int main()
{
	// open file
       SF_INFO fileInfo;

       SNDFILE* file_sf = sf_open("mytest.ogg", SFM_READ, &fileInfo);
	
	// seek
	sf_count_t startSample = 389999;
	sf_count_t framesSeeked = sf_seek(file_sf, startSample, SEEK_SET);

        std::cout << "startSample: " << startSample << std::endl;
	std::cout << "framesSeeked: " << framesSeeked << std::endl;
	
	// read
	sf_count_t framesRead = 0;
	
	size_t frameSize = 65536;
	size_t sizeInBytes = 4 * frameSize * 2;// type size * num samples * num channels
	uint8_t* buffer = new uint8_t[sizeInBytes];
	
	framesRead = sf_readf_float(file_sf, reinterpret_cast<float*>(buffer), frameSize);
	
        std::cout << "frameSize: " << frameSize << std::endl;
	std::cout << "sizeInBytes: " << sizeInBytes << std::endl;
	std::cout << "framesRead: " << framesRead << std::endl;
	
	sf_close(file_sf);

    return 0;

}
```

For this example, the total number of samples is 396519. If we start at 389999 and try to read a framesize (65536) we should get all the remaining samples in the file - 6520. But with 1.0.30 release I only get 5496 (missing 1024 samples).

Here is the output of the above repro code for 1.0.28:
```
startSample: 389999
framesSeeked: 389999
frameSize: 65536
sizeInBytes: 524288
framesRead: 6520
```
And for 1.0.30:
```
startSample: 389999
framesSeeked: 389999
frameSize: 65536
sizeInBytes: 524288
framesRead: 5496
```
(both ran on macOS 10.15.3, but we see the issue on Windows too)

The file used in the example is attached - [mytest.zip](https://github.com/libsndfile/libsndfile/files/5425485/mytest.zip). It was randomly generated, but I see this issue on other .ogg files that are long enough. Here is the snd-info output:
```
$ sndfile-info mytest.ogg 
========================================
File : mytest.ogg
Length : 504453
Ogg stream data : Vorbis
Stream serialno : 536000084
Vorbis library version : Xiph.Org libVorbis 1.3.6
Bitstream is 2 channel, 44100 Hz
Encoded by : Xiph.Org libVorbis I 20200704 (Reducing Environment)
End

----------------------------------------
Sample Rate : 44100
Frames      : 396519
Channels    : 2
Format      : 0x00200060
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:08.991
Signal Max  : 1.21788 (-88.60 dB)
```

Does this look familiar to anyone? Is this a bug introduced in 1.0.29 or 1.0.30, or is there something else going on here?

Thanks!

### PR DESCRIPTION
**Pull request by arthurt**
Previously the `vorbis_seek()` function did not take the lapped nature of Vorbis block into account when using the bisection search.

Also, introduces `vorbis_skip()`, which can skip through packets without having to decode all the way to samples.

Fixes #643

### CODE REVIEW

**Comment by evpobr** [comment]
Great, you took the time, thanks. You have done all the work, so it will be fair if you moderate the changes.

PS Did you see #705? What do you think?

**Comment by arthurt** [comment]
> PS Did you see #705? What do you think?

I agree with it. I would add, I do like the practice of if a commit deals with one feature or source prefixing the commit with the name of it followed by a colon. eg the `ogg_vorbis: Change blah` or `ogg: Do blah`. Thoughts?

**Comment by evpobr** [comment]
Let's continue the discussion in #705.

**Review by evpobr — APPROVED** [review]

**Comment by Be-ing** [comment]
Mixxx tests [still fail](https://github.com/Be-ing/mixxx/runs/1908562676?check_suite_focus=true#step:19:6434)

**Pull request merged**
