### PR TITLE
Improving header documentation.

### PR DESCRIPTION
**Pull request by SmiVan**
Working on #674 and similar cases of reserved header data if there is any.

### CODE REVIEW

**Comment by SmiVan** [comment]
Waiting for confirmation on whether or not dithering will be implemented in the future after all or deprecated.

**Comment by evpobr** [comment]
> Waiting for confirmation on whether or not dithering will be implemented in the future after all or deprecated.

Not deprecated.

**Comment by evpobr** [comment]
@SmiVan , is it ready?

**Comment by evpobr** [comment]
@SmiVan ? It is still draft. Comment please.

**Comment by SmiVan** [comment]
Feel free to merge it now, I'll submit another pull request if I make more improvements.

**Comment by evpobr** [comment]
Thanks @SmiVan , waiting for new contributions.

**Pull request merged**
