### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by SoapGentoo**

### CODE REVIEW

**Comment by SoapGentoo** [comment]
Linux install Autotools tree:
```
tmp/
└── usr
    └── local
        ├── bin
        │   ├── sndfile-cmp
        │   ├── sndfile-concat
        │   ├── sndfile-convert
        │   ├── sndfile-deinterleave
        │   ├── sndfile-info
        │   ├── sndfile-interleave
        │   ├── sndfile-metadata-get
        │   ├── sndfile-metadata-set
        │   ├── sndfile-play
        │   └── sndfile-salvage
        ├── include
        │   ├── sndfile.h
        │   └── sndfile.hh
        ├── lib
        │   ├── libsndfile.la
        │   ├── libsndfile.so -> libsndfile.so.1.1.0
        │   ├── libsndfile.so.1 -> libsndfile.so.1.1.0
        │   ├── libsndfile.so.1.1.0
        │   └── pkgconfig
        │       └── sndfile.pc
        └── share
            ├── doc
            │   └── libsndfile
            │       ├── api.md
            │       ├── bugs.md
            │       ├── command.md
            │       ├── embedded_files.md
            │       ├── FAQ.md
            │       ├── formats.md
            │       ├── index.md
            │       ├── libsndfile.css
            │       ├── libsndfile.jpg
            │       ├── lists.md
            │       ├── new_file_type_howto.md
            │       ├── octave.md
            │       ├── print.css
            │       ├── sndfile_info.md
            │       ├── tutorial.md
            │       └── win32.md
            └── man
                └── man1
                    ├── sndfile-cmp.1
                    ├── sndfile-concat.1
                    ├── sndfile-convert.1
                    ├── sndfile-deinterleave.1
                    ├── sndfile-info.1
                    ├── sndfile-interleave.1
                    ├── sndfile-metadata-get.1
                    ├── sndfile-metadata-set.1
                    ├── sndfile-play.1
                    └── sndfile-salvage.1
```

Linux CMake install tree:
```
tmp/
└── usr
    └── local
        ├── bin
        │   ├── sndfile-cmp
        │   ├── sndfile-concat
        │   ├── sndfile-convert
        │   ├── sndfile-deinterleave
        │   ├── sndfile-info
        │   ├── sndfile-interleave
        │   ├── sndfile-metadata-get
        │   ├── sndfile-metadata-set
        │   ├── sndfile-play
        │   └── sndfile-salvage
        ├── include
        │   ├── sndfile.h
        │   └── sndfile.hh
        ├── lib64
        │   ├── cmake
        │   │   └── SndFile
        │   │       ├── SndFileConfig.cmake
        │   │       ├── SndFileConfigVersion.cmake
        │   │       ├── SndFileTargets.cmake
        │   │       └── SndFileTargets-noconfig.cmake
        │   ├── libsndfile.so -> libsndfile.so.1
        │   ├── libsndfile.so.1 -> libsndfile.so.1.1.0
        │   ├── libsndfile.so.1.1.0
        │   └── pkgconfig
        │       └── sndfile.pc
        └── share
            ├── doc
            │   └── libsndfile
            │       ├── api.md
            │       ├── bugs.md
            │       ├── command.md
            │       ├── embedded_files.md
            │       ├── FAQ.md
            │       ├── formats.md
            │       ├── index.md
            │       ├── libsndfile.css
            │       ├── libsndfile.jpg
            │       ├── lists.md
            │       ├── new_file_type_howto.md
            │       ├── octave.md
            │       ├── print.css
            │       ├── sndfile_info.md
            │       ├── tutorial.md
            │       └── win32.md
            └── man
                └── man1
                    ├── sndfile-cmp.1
                    ├── sndfile-concat.1
                    ├── sndfile-convert.1
                    ├── sndfile-deinterleave.1
                    ├── sndfile-info.1
                    ├── sndfile-interleave.1
                    ├── sndfile-metadata-get.1
                    ├── sndfile-metadata-set.1
                    ├── sndfile-play.1
                    └── sndfile-salvage.1
```

**Comment by SoapGentoo** [comment]
working on macOS builds...

**Comment by evpobr** [comment]
I guess ABI bump is  not correct, no new exported symbols added, so it is patch bump.

**Comment by SoapGentoo** [comment]
where do you see an ABI bump?

**Comment by SoapGentoo** [comment]
macOS:
```
autotools-macos/
└── usr
    └── local
        ├── bin
        │   ├── sndfile-cmp
        │   ├── sndfile-concat
        │   ├── sndfile-convert
        │   ├── sndfile-deinterleave
        │   ├── sndfile-info
        │   ├── sndfile-interleave
        │   ├── sndfile-metadata-get
        │   ├── sndfile-metadata-set
        │   ├── sndfile-play
        │   └── sndfile-salvage
        ├── include
        │   ├── sndfile.h
        │   └── sndfile.hh
        ├── lib
        │   ├── libsndfile.1.1.0.dylib
        │   ├── libsndfile.1.dylib -> libsndfile.1.1.0.dylib
        │   ├── libsndfile.dylib -> libsndfile.1.1.0.dylib
        │   ├── libsndfile.la
        │   └── pkgconfig
        │       └── sndfile.pc
        └── share
            ├── doc
            │   └── libsndfile
            │       ├── FAQ.md
            │       ├── api.md
            │       ├── bugs.md
            │       ├── command.md
            │       ├── embedded_files.md
            │       ├── formats.md
            │       ├── index.md
            │       ├── libsndfile.css
            │       ├── libsndfile.jpg
            │       ├── lists.md
            │       ├── new_file_type_howto.md
            │       ├── octave.md
            │       ├── print.css
            │       ├── sndfile_info.md
            │       ├── tutorial.md
            │       └── win32.md
            └── man
                └── man1
                    ├── sndfile-cmp.1
                    ├── sndfile-concat.1
                    ├── sndfile-convert.1
                    ├── sndfile-deinterleave.1
                    ├── sndfile-info.1
                    ├── sndfile-interleave.1
                    ├── sndfile-metadata-get.1
                    ├── sndfile-metadata-set.1
                    ├── sndfile-play.1
                    └── sndfile-salvage.1

$ otool -L autotools-macos/usr/local/lib/libsndfile.dylib
autotools-macos/usr/local/lib/libsndfile.dylib:
    /usr/local/lib/libsndfile.1.dylib (compatibility version 3.0.0, current version 3.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

CMake:
```
cmake-macos/
└── usr
    └── local
        ├── bin
        │   ├── sndfile-cmp
        │   ├── sndfile-concat
        │   ├── sndfile-convert
        │   ├── sndfile-deinterleave
        │   ├── sndfile-info
        │   ├── sndfile-interleave
        │   ├── sndfile-metadata-get
        │   ├── sndfile-metadata-set
        │   ├── sndfile-play
        │   └── sndfile-salvage
        ├── include
        │   ├── sndfile.h
        │   └── sndfile.hh
        ├── lib
        │   ├── cmake
        │   │   └── SndFile
        │   │       ├── SndFileConfig.cmake
        │   │       ├── SndFileConfigVersion.cmake
        │   │       ├── SndFileTargets-noconfig.cmake
        │   │       └── SndFileTargets.cmake
        │   ├── libsndfile.1.1.0.dylib
        │   ├── libsndfile.1.dylib -> libsndfile.1.1.0.dylib
        │   ├── libsndfile.dylib -> libsndfile.1.dylib
        │   └── pkgconfig
        │       └── sndfile.pc
        └── share
            ├── doc
            │   └── libsndfile
            │       ├── FAQ.md
            │       ├── api.md
            │       ├── bugs.md
            │       ├── command.md
            │       ├── embedded_files.md
            │       ├── formats.md
            │       ├── index.md
            │       ├── libsndfile.css
            │       ├── libsndfile.jpg
            │       ├── lists.md
            │       ├── new_file_type_howto.md
            │       ├── octave.md
            │       ├── print.css
            │       ├── sndfile_info.md
            │       ├── tutorial.md
            │       └── win32.md
            └── man
                └── man1
                    ├── sndfile-cmp.1
                    ├── sndfile-concat.1
                    ├── sndfile-convert.1
                    ├── sndfile-deinterleave.1
                    ├── sndfile-info.1
                    ├── sndfile-interleave.1
                    ├── sndfile-metadata-get.1
                    ├── sndfile-metadata-set.1
                    ├── sndfile-play.1
                    └── sndfile-salvage.1

$ otool -L cmake-macos/usr/local/lib/libsndfile.dylib
cmake-macos/usr/local/lib/libsndfile.dylib:
    @rpath/libsndfile.1.dylib (compatibility version 3.0.0, current version 3.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

The only thing I'm slightly worried is the difference to the current release:
```
$ otool -L /opt/local/lib/libsndfile.dylib
/opt/local/lib/libsndfile.dylib:
    /opt/local/lib/libsndfile.1.dylib (compatibility version 2.0.0, current version 2.31.0)
[...]
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

**Comment by evpobr** [comment]
I see it in .so name.

**Comment by evpobr** [comment]
c:r:a should be 1:33:0 -> 1:34:0

**Comment by SoapGentoo** [comment]
sure, but the `SONAME` is still the same:
```
$ readelf -d tmp/usr/local/lib/libsndfile.so.1.1.0 | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libsndfile.so.1]
```
but let's go with `1:34:0` instead

**Comment by evpobr** [comment]
We have compatible additions in API (header), so we bump 1.0.31 -> 1.1.0 as SemVer says.

But we have ho changes at binary interface level (so), no new entry point etc, so it is just small bump to ABI: 1.0.33 -> 1.0.34.

**Comment by SoapGentoo** [comment]
(btw, this goes back to the point that API and ABI can't be versioned automatically together)

**Comment by evpobr** [comment]
Wy not? We have different variables for API and ABI. And they don't have to be the same at all.

**Comment by SoapGentoo** [comment]
> Wy not? We have different variables for API and ABI. And they don't have to be the same at all.

I'm just reiterating that approaches likes those mentioned in https://github.com/libsndfile/libsamplerate/issues/140#issuecomment-765005303 just can't work in general

**Comment by SoapGentoo** [comment]
Now:
```
$ tree tmp/usr/local/lib/
tmp/usr/local/lib/
├── libsndfile.la
├── libsndfile.so -> libsndfile.so.1.0.34
├── libsndfile.so.1 -> libsndfile.so.1.0.34
├── libsndfile.so.1.0.34
└── pkgconfig
    └── sndfile.pc

1 directory, 5 files
```

**Comment by evpobr** [comment]
We just need to check more carefully.

In addition, 'src_clone` was a release from @erikd, and he did not follow the rules of libtool versioning.

**Comment by SoapGentoo** [comment]
@evpobr changed, can you push any other changes to this branch please? like changelog and what not

**Comment by evpobr** [comment]
Ok, wait a little.

**Comment by evpobr** [comment]
It is done. Complete release, i will add Win32 binaries later.

**Review by evpobr — APPROVED** [review]

**Pull request merged**
