### PR TITLE
Let wav parsing recover from invalid LIST chunks, fixing #374

### PR DESCRIPTION
**Pull request by kiilerix**
This triggered other minor fixes and cleanup. See the individual commits.

### CODE REVIEW

**Comment by evpobr** [comment]
Hi @kiilerix , impressive work! @arthurt , can you take a look?

**Review by arthurt — APPROVED** [review]

**Comment by arthurt** [comment]
It's less invasive that #884 .

**Comment by kiilerix** [comment]
> It's less invasive than #884 .

I wasn't aware of that one ... or whether it solves the same problem. It seems to have some nice things. And some that seems more debatable. But too much happening at once makes it hard to tell, so IMO that one should be reworked anyway ... hopefully after being rebased on top of this one.

**Comment by arthurt** [comment]
:+1: I think #884 should be deferred for your PR.

**Review by evpobr — APPROVED** [review]

**Comment by evpobr** [comment]
Thanks @kiilerix !

**Comment by evpobr** [comment]
I suggest accepting this pull request if it helps right now. @arthurt ?

**Comment by evpobr** [comment]
Ah, you approved. Ok then.

**Pull request merged**
