### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by SoapGentoo**
doing the tarball diffs on Linux and macOS in the mean time

### CODE REVIEW

**Comment by evpobr** [comment]
@SoapGentoo , API is 1.2.0. We have added `SFC_GET_OGG_STREAM_SERIALNO` command.

**Comment by SoapGentoo** [comment]
@evpobr is this the layout we want (I haven't pushed the changes yet):
```
--- 1.1.0_LAYOUT	2022-12-25 10:59:53.723655663 +0100
+++ 1.1.1_LAYOUT	2022-12-25 11:05:18.000528392 +0100
@@ -17,9 +17,9 @@
         │   └── sndfile.hh
         ├── lib
         │   ├── libsndfile.la
-        │   ├── libsndfile.so -> libsndfile.so.1.0.34
-        │   ├── libsndfile.so.1 -> libsndfile.so.1.0.34
-        │   ├── libsndfile.so.1.0.34
+        │   ├── libsndfile.so -> libsndfile.so.1.1.0
+        │   ├── libsndfile.so.1 -> libsndfile.so.1.1.0
+        │   ├── libsndfile.so.1.1.0
         │   └── pkgconfig
         │       └── sndfile.pc
         └── share
```

**Comment by SoapGentoo** [comment]
@evpobr now:
```
--- 1.1.0 LAYOUT
+++ 1.2.0 LAYOUT
@@ -17,9 +17,9 @@
         │   └── sndfile.hh
         ├── lib
         │   ├── libsndfile.la
-        │   ├── libsndfile.so -> libsndfile.so.1.0.34
-        │   ├── libsndfile.so.1 -> libsndfile.so.1.0.34
-        │   ├── libsndfile.so.1.0.34
+        │   ├── libsndfile.so -> libsndfile.so.1.2.0
+        │   ├── libsndfile.so.1 -> libsndfile.so.1.2.0
+        │   ├── libsndfile.so.1.2.0
         │   └── pkgconfig
         │       └── sndfile.pc
         └── share
```

**Comment by evpobr** [comment]
API - correct now.


ABI - revision bump :

```m4
m4_define([lt_current], [1])
m4_define([lt_revision], [35])
m4_define([lt_age], [0])
```

**Comment by evpobr** [comment]
if you don't mind, I'll bump release version numbers next time.

**Comment by SoapGentoo** [comment]
yes, please prepare everything necessary for a release next time

**Comment by SoapGentoo** [comment]
```
--- 1.1.0
+++ 1.2.0
@@ -17,9 +17,9 @@
         │   └── sndfile.hh
         ├── lib
         │   ├── libsndfile.la
-        │   ├── libsndfile.so -> libsndfile.so.1.0.34
-        │   ├── libsndfile.so.1 -> libsndfile.so.1.0.34
-        │   ├── libsndfile.so.1.0.34
+        │   ├── libsndfile.so -> libsndfile.so.1.0.35
+        │   ├── libsndfile.so.1 -> libsndfile.so.1.0.35
+        │   ├── libsndfile.so.1.0.35
         │   └── pkgconfig
         │       └── sndfile.pc
         └── share
```

**Comment by evpobr** [comment]
Above layout is correct, but i don't see new commit.

**Comment by SoapGentoo** [comment]
macOS:
```
--- 1.1.0
+++ 1.2.0
@@ -16,9 +16,9 @@
         │   ├── sndfile.h
         │   └── sndfile.hh
         ├── lib
-        │   ├── libsndfile.1.0.34.dylib
-        │   ├── libsndfile.1.dylib -> libsndfile.1.0.34.dylib
-        │   ├── libsndfile.dylib -> libsndfile.1.0.34.dylib
+        │   ├── libsndfile.1.0.35.dylib
+        │   ├── libsndfile.1.dylib -> libsndfile.1.0.35.dylib
+        │   ├── libsndfile.dylib -> libsndfile.1.0.35.dylib
         │   ├── libsndfile.la
         │   └── pkgconfig
         │       └── sndfile.pc
```
and otool:
```
--- 1.1.0
+++ 1.2.0
@@ -1,5 +1,5 @@
-	/usr/local/lib/libsndfile.1.dylib (compatibility version 2.0.0, current version 2.34.0)
+	/usr/local/lib/libsndfile.1.dylib (compatibility version 2.0.0, current version 2.35.0)
 	/opt/local/lib/libFLAC.8.dylib (compatibility version 12.0.0, current version 12.0.0)
 	/opt/local/lib/libvorbis.0.dylib (compatibility version 5.0.0, current version 5.9.0)
 	/opt/local/lib/libvorbisenc.2.dylib (compatibility version 3.0.0, current version 3.12.0)
```

**Review by evpobr — APPROVED** [review]

**Pull request merged**
