### PR TITLE
Add move semantics for SndfileHandle if C++11 or newer

### PR DESCRIPTION
**Pull request by haydaralaidrus**
Adding move constructor and move assignment for `SndfileHandle` if the C++11 std or newer is supported.

### CODE REVIEW

**Comment by evpobr** [comment]
Hi @haydaralaidrus .

**Review by evpobr — COMMENTED** [review]
I'm not sure, in C++11 mode do we need to mark copy constructor and copy assignment operator as deleted?

**Comment by haydaralaidrus** [comment]
Hi @evpobr !,

Do you mean in this particular case or in general? Im sorry if i don't follow your question. But, if you want to prevent the compiler from generating the default copy constructor and copy assignment, yes. Either delete them or define them ourselves. I don't see why it is necessary to delete it here, though.

**Comment by evpobr** [comment]
Ok then.

**Comment by evpobr** [comment]
Thanks @haydaralaidrus !

**Comment by haydaralaidrus** [comment]
@evpobr no problem!

**Pull request merged**
