### PR TITLE
sndfile-convert: fix typo in error message

### PR DESCRIPTION
**Pull request by fjl**

### CODE REVIEW

**Comment by evpobr** [comment]
Hi @fjl . Thanks for this pull request.

**Review by evpobr — APPROVED** [review]

**Comment by evpobr** [comment]
Thanks @fjl !

**Comment by fjl** [comment]
I just think 'not able to' sounds kind of weird. But good to see you have rephrased it to your liking.

**Comment by evpobr** [comment]
I hope that didn't upset you. I just wanted to commit a useful change as quickly as possible. If there are no issues with correcting the typo, then another wording may raise questions and delay the adoption of the code.

**Comment by fjl** [comment]
Hey, don't worry about upsetting me :) I think we can all agree that this PR is just fixing a typo, it is not the most important thing in the world.

**Pull request merged**
