### PR TITLE
flac: Fix improper buffer reusing

### PR DESCRIPTION
**Pull request by yuawn**
See #731 .

### CODE REVIEW

**Comment by evpobr** [comment]
@arthurt , can you look at this?

**Comment by evpobr** [comment]
It looks like @arthurt is busy, no activity in his repos.

@bobsayshilol, could you review it?

**Review by bobsayshilol — CHANGES_REQUESTED** [review]
I can confirm that this PR makes the crash go away, however I don't believe that this is the correct solution to the problem.

The underlying issue is that the return value of `FLAC__stream_decoder_process_single()` isn't correctly handled here: https://github.com/libsndfile/libsndfile/blob/4c30646abf7834e406f7e2429c70bc254e18beab/src/flac.c#L957-L967

According to the documentation at https://xiph.org/flac/api/group__flac__stream__decoder.html#ga9d6df4a39892c05955122cf7f987f856 it returns `false if any fatal read, write, or memory allocation error occurred (meaning decoding must stop), else true` so we should be dropping into the branch below and setting `pflac->frame = NULL` so that the next read doesn't read from a now bogus frame, which is currently what's happening since `pflac->frame` is pointing to an outdated/corrupt frame inside `FLAC`.

**Comment by evpobr** [comment]
@yuawn , would you be so kind as to update the pull request?

**Comment by yuawn** [comment]
Hi @evpobr,

Thank @bobsayshilol, I have updated the pull request.
This commit can fix the root cause of this security bug, and it should be merge and release as soon as possible, because the vulnerability affects wild range of release version.

**Comment by evpobr** [comment]
Funny, the fix is so simple. @bobsayshilol , approve?

**Review by bobsayshilol — APPROVED** [review]
LGTM. Note that `psf_log_printf()` isn't being called like in the branch below though, but functionally it's now correct.

**Comment by yuawn** [comment]
@evpobr, done!

**Comment by evpobr** [comment]
Thank you all for your help!

**Pull request merged**
